---

- name: Filesystem cleanup
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /var/cache/apt/archives/*.deb
    - /var/cache/apt/archives/partial/*
    - /var/cache/debconf/*-old
    - /var/lib/apt/lists/*
