---

- name: Configure postfix
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^[\s;]*{{ item.variable }}[\s]*='
    line:   '{{ item.variable }} = {{ item.value }}'
  with_items: "{{ POSTFIX_VARS }}"
  when: item.value != ""