---

- name: Configure postfix
  lineinfile:
    dest:   /etc/postfix/main.cf
    regexp: '^[\s]*{{ item.key }}[\s]*='
    line:   '{{ item.key }}={{ item.value }}'
  with_items:
   - { key: 'myhostname',     value: '{{ ansible_hostname }}' }
   - { key: 'mydestination',  value: '{{ ansible_hostname }}' }